name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Dumela, lefase"
      - name: multiline scrippt
        run: |
          node -v
          npm -v